### ISSUE TITLE
uncompress files before searching

### ISSUE THREAD

**Issue by eighthave** [jedisct1/ipgrep#4]
I wonder if it makes sense to have `ipgrep` automatically uncompress files before running the searches on them.  Things like ZIP/JAR/APK, tarballs, etc. should be pretty easily to handle automatically.

**Comment by jedisct1** [comment]
That can be done by a helper script. Just using the shell would be way easier than Python for that kind of task.

**Comment by eighthave** [comment]
yeah, makes sense, that's what I'm doing now.
